# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin
 
    jobs:
    
    - job: Android
      pool:
        vmImage: 'macOS 10.13'
        
      variables:
        buildConfiguration: 'Release'
        outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
        
      steps:
      - task: NuGetToolInstaller@0
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
          
      - task: XamarinAndroid@1
        inputs:
          projectFile: '**/*Droid*.csproj'
          outputDirectory: '$(outputDirectory)'
          configuration: '$(buildConfiguration)'
          
      - task: AndroidSigning@3
        inputs:
          apksign: false
          zipalign: false
          apkFiles: '$(outputDirectory)/*.apk'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(outputDirectory)'
          #jarsign: true
          #jarsignerKeystoreFile: 'pathToYourKeystoreFile'
          #jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
          #jarsignerKeystoreAlias: 'yourKeystoreAlias'
          #jarsignerKeyPassword: '$(jarsignerKeyPassword)'
          
      
    - job: iOS
      pool:
        vmImage: 'macOS-10.13'
        
      variables:
        buildConfiguration: 'Release'
        
      steps:
      - task: NuGetToolInstaller@0
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
          
      - task: XamariniOS@2
        inputs:
          solutionFile: '**/*.sln'
          configuration: '$(buildConfiguration)'
          buildForSimulator: true
          #clean: false # Optional
          packageApp: false
          runNugetRestore: false 
          #args: # Optional
          #workingDirectory: # Optional
          #mdtoolFile: # Optional
          #signingIdentity: # Optional
          #signingProvisioningProfileID: # Optional     
